# 基础环境，选择带有预装 Yarn 的 Node.js 镜像
FROM node:18-alpine

# 工作目录
WORKDIR /app

# 复制依赖文件
COPY ./package.json ./yarn.lock ./

# 安装依赖
RUN yarn install

# 拷贝其他内容
COPY ./ ./

# 暴露端口
EXPOSE 5173

# 启动项目
CMD [ "yarn", "dev" ]


