version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev # 指定 Dockerfile 文件
    ports:
      - "5173:5173"
    volumes: # 挂载本地文件到容器
      - /app/node_modules # 防止容器中的 node_modules 覆盖本地的 node_modules
      - ./:/app # 挂载当前目录到容器的 /app 目录
  other:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["yarn", "lint"] # 覆盖默认的启动命令
